### ISSUE TITLE
隐藏直播页商品提示

### ISSUE THREAD

**Issue by tuntun0609** [tuntun0609/tun-bili-tool#84]
```css
.shop-popover {
  display: none
}
```
![image](https://github.com/tuntun0609/tun-bili-tool/assets/56946732/7e3b9fd3-e837-490d-9043-efb14239ba71)
